/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Cliente_Compra extends javax.swing.JFrame {
   private static List<Productos_T_Madre> ingresoP =Ingreso_de_Productos_alas_Perchas.getIngresoP();
   Productos_T_Madre poTemporal;
   
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo1 = new DefaultTableModel();
    public void CTotal(){
        double total = 0;
        for (int i = 0; i <modelo.getRowCount(); i++) {
            total=total+Double.parseDouble(modelo.getValueAt(i,4).toString())+Double.parseDouble(modelo.getValueAt(i,5).toString());
            
            
        }
        total_Pagar_F.setText(String.valueOf(total));
    }
    public void CargaDatos() {
        ArrayList<Object> nombreColumna = new ArrayList<Object>();
        nombreColumna.add("Tipo");
        nombreColumna.add("Nombre.P");
        nombreColumna.add("Cantidad");
        nombreColumna.add("F.caducidad");
        nombreColumna.add("Iva");
        nombreColumna.add("Subtotal");
 
        for(Object columna : nombreColumna){
        modelo.addColumn(columna);
        }
        this.Tabla.setModel(modelo);
        

    }

    /**
     * Creates new form Cliente_Compra
     */
    public Cliente_Compra() {
        initComponents();
        CargaDatos();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
          ArrayList<Object> nombreColumna = new ArrayList<Object>();
        nombreColumna.add("Tipo");
        nombreColumna.add("Nombre.P");
        nombreColumna.add("Id");
        nombreColumna.add("Precio");
        nombreColumna.add("Caducidad");
    
        for(Object columna : nombreColumna){
        modelo1.addColumn(columna);
        }
        this.P_Tabla.setModel(modelo1);
        //------------------------------------
       
        Ingreso_de_Productos_alas_Perchas pU = new Ingreso_de_Productos_alas_Perchas();
        String []info =new String[5];
  
        
        for (Productos_T_Madre poC : pU.getProductos()) {
                info[0]= poC.getTipo();
                info[1]= poC.getNombre() ;
                info[2]=poC.getId() ;
                info[3]=String.valueOf(poC.getPrecio());
                info[4]= poC.getCaducidad() ;
                
           modelo1.addRow(info);
        }
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ID_Buscar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Seleccionar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        buscarProdu = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nro_Pro = new javax.swing.JTextField();
        Produ_Tabla = new javax.swing.JLabel();
        txt_Iva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total_Pagar_F = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        presentar_nombre = new javax.swing.JLabel();
        PresentarID = new javax.swing.JLabel();
        Nombre_cliente = new javax.swing.JTextField();
        IDCLIENTE = new javax.swing.JTextField();
        Factura = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        P_Tabla = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(74, 25, 0, 0);

        ID_Buscar.setBackground(new java.awt.Color(204, 204, 255));
        ID_Buscar.setFont(new java.awt.Font("Tw Cen MT", 0, 11)); // NOI18N
        getContentPane().add(ID_Buscar);
        ID_Buscar.setBounds(104, 43, 124, 30);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jLabel3.setText("Ingrese el Id:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 46, 59, 15);

        Seleccionar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(Seleccionar);
        Seleccionar.setBounds(310, 240, 85, 23);

        Atras.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras);
        Atras.setBounds(20, 320, 57, 23);

        Buscar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar);
        Buscar.setBounds(150, 320, 63, 23);

        buscarProdu.setBackground(new java.awt.Color(102, 102, 102));
        buscarProdu.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        buscarProdu.setForeground(new java.awt.Color(0, 51, 51));
        buscarProdu.setText("Producto Buscado");
        getContentPane().add(buscarProdu);
        buscarProdu.setBounds(70, 260, 82, 13);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Ingrese los datos:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 100, 160, 14);

        Nro_Pro.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(Nro_Pro);
        Nro_Pro.setBounds(370, 140, 60, 20);

        Produ_Tabla.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        Produ_Tabla.setText("IVa:");
        getContentPane().add(Produ_Tabla);
        Produ_Tabla.setBounds(290, 180, 34, 13);

        txt_Iva.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(txt_Iva);
        txt_Iva.setBounds(340, 180, 60, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel7.setText("Nro.Productos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 140, 80, 13);

        jLabel2.setFont(new java.awt.Font("Teko SemiBold", 2, 11)); // NOI18N
        jLabel2.setText("Total a Pagar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 350, 270, 20);

        total_Pagar_F.setText("0,00");
        getContentPane().add(total_Pagar_F);
        total_Pagar_F.setBounds(970, 350, 50, 20);

        jLabel6.setText("%");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 180, 34, 14);

        jLabel10.setFont(new java.awt.Font("Teko SemiBold", 1, 11)); // NOI18N
        jLabel10.setText("Nombre del Cliente");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(460, 50, 100, 30);

        jLabel11.setFont(new java.awt.Font("Teko SemiBold", 1, 11)); // NOI18N
        jLabel11.setText("ID del Cliente");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(800, 60, 80, 17);

        jLabel12.setFont(new java.awt.Font("Teko SemiBold", 2, 11)); // NOI18N
        jLabel12.setText("Nombre:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 300, 70, 17);

        jLabel13.setFont(new java.awt.Font("Teko SemiBold", 2, 11)); // NOI18N
        jLabel13.setText("ID");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 330, 70, 17);
        getContentPane().add(presentar_nombre);
        presentar_nombre.setBounds(910, 290, 110, 20);
        getContentPane().add(PresentarID);
        PresentarID.setBounds(900, 320, 120, 20);

        Nombre_cliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(Nombre_cliente);
        Nombre_cliente.setBounds(560, 50, 230, 30);

        IDCLIENTE.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(IDCLIENTE);
        IDCLIENTE.setBounds(870, 50, 130, 30);

        Factura.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Factura.setText("Factura");
        Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaActionPerformed(evt);
            }
        });
        getContentPane().add(Factura);
        Factura.setBounds(450, 380, 69, 23);

        Salir.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(920, 380, 53, 23);

        Tabla.setBackground(new java.awt.Color(204, 255, 204));
        Tabla.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(460, 90, 560, 200);

        P_Tabla.setBackground(new java.awt.Color(204, 255, 204));
        P_Tabla.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        P_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(P_Tabla);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(10, 90, 260, 150);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setText("Buscar Productos");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(50, 10, 160, 19);

        jLabel5.setBackground(new java.awt.Color(153, 255, 153));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, 0, 450, 410);

        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 60, 40, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("Factura");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 10, 60, 15);

        jLabel8.setBackground(new java.awt.Color(153, 255, 204));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 0, 610, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
  Ingreso_de_Productos_alas_Perchas pU = new Ingreso_de_Productos_alas_Perchas();
        String idB = ID_Buscar.getText();

        int cantidad = Integer.parseInt(Nro_Pro.getText());
        double Iva = Double.parseDouble(txt_Iva.getText());
        Iva = Iva / 100;
        double Total = 0;
        String []info =new String[6];
        
       

        Productos_T_Madre poC = poTemporal;
            double precio = (((poC.getPrecio() * cantidad) * Iva) + (poC.getPrecio() * cantidad));
         

                info[0]= poC.getTipo();
                info[1]= poC.getNombre() ;
                info[2]=String.valueOf(cantidad) ;
                info[3]= poC.getCaducidad() ;
                
                info[4]=String.valueOf(poC.getPrecio()) ;
                info[5]=String.valueOf(precio);
                
              
                modelo.addRow(info);
                Tabla.setModel(modelo);
                System.out.println(info);
         
            CTotal();
            

        
     
        
       
    }//GEN-LAST:event_SeleccionarActionPerformed
  


    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        // presentar formulario menu
        Menu me = new Menu();
        me.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:

        Ingreso_de_Productos_alas_Perchas pU = new Ingreso_de_Productos_alas_Perchas();

        int idB =Integer.parseInt( ID_Buscar.getText());
        for (Productos_T_Madre poC : pU.getProductos()) {
               
            if (idB==Integer.parseInt(poC.getId())) {
                
              
                buscarProdu.setText(poC.getNombre());
                poTemporal=poC;
                break;

            } else {
                buscarProdu.setText("No existe el producto");

            }
        }
        
       

    }//GEN-LAST:event_BuscarActionPerformed

    private void FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaActionPerformed
        // TODO add your handling code here:

        String nombreC = Nombre_cliente.getText();
        String id = IDCLIENTE.getText();
        presentar_nombre.setText(nombreC);
        PresentarID.setText(id);
    }//GEN-LAST:event_FacturaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed
    public void limpiar_productos() {
        int fila = Tabla.getRowCount();
        for (int i = fila-1; i >= 10; i--) {
            modelo.removeRow(i);
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Factura;
    private javax.swing.JTextField IDCLIENTE;
    private javax.swing.JTextField ID_Buscar;
    private javax.swing.JTextField Nombre_cliente;
    private javax.swing.JTextField Nro_Pro;
    private javax.swing.JTable P_Tabla;
    private javax.swing.JLabel PresentarID;
    private javax.swing.JLabel Produ_Tabla;
    private javax.swing.JButton Salir;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel buscarProdu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel presentar_nombre;
    private javax.swing.JLabel total_Pagar_F;
    private javax.swing.JTextField txt_Iva;
    // End of variables declaration//GEN-END:variables
}
