/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_poo;

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Ingreso_productos = new javax.swing.JButton();
        SistemaFacturacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SalirC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 80, 67, 15);

        Ingreso_productos.setFont(new java.awt.Font("Tempus Sans ITC", 2, 11)); // NOI18N
        Ingreso_productos.setText("Ingreso de productos");
        Ingreso_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingreso_productosActionPerformed(evt);
            }
        });
        getContentPane().add(Ingreso_productos);
        Ingreso_productos.setBounds(110, 120, 150, 23);

        SistemaFacturacion.setFont(new java.awt.Font("Tempus Sans ITC", 2, 11)); // NOI18N
        SistemaFacturacion.setText("Sistema de Facturacion");
        SistemaFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SistemaFacturacionActionPerformed(evt);
            }
        });
        getContentPane().add(SistemaFacturacion);
        SistemaFacturacion.setBounds(110, 190, 143, 23);

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Teko SemiBold", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Comercial Ordoñez S.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 10, 250, 30);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setFont(new java.awt.Font("Teko SemiBold", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("____Bienvenido____");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(113, 39, 140, 21);

        SalirC.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        SalirC.setForeground(new java.awt.Color(255, 0, 0));
        SalirC.setText("Salir");
        SalirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirCActionPerformed(evt);
            }
        });
        getContentPane().add(SalirC);
        SalirC.setBounds(160, 250, 53, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_poo/unnamed.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ingreso_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingreso_productosActionPerformed
        // TODO add your handling code here:
        Ingreso_de_Productos_alas_Perchas InPP = new  Ingreso_de_Productos_alas_Perchas();
        InPP.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Ingreso_productosActionPerformed

    private void SistemaFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaFacturacionActionPerformed
        // TODO add your handling code here:
        Cliente_Compra CC = new Cliente_Compra();
        CC.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_SistemaFacturacionActionPerformed

    private void SalirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirCActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingreso_productos;
    private javax.swing.JButton SalirC;
    private javax.swing.JButton SistemaFacturacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
