/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_factura;

/**
 *
 * @author DELL
 */
public class Factura_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Factura_GUI
     */
    public Factura_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        C_subtotal = new javax.swing.JButton();
        T_Iva = new javax.swing.JButton();
        T_Descuento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 204));
        setIconImages(null);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 204, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("Calculo de presupuesto de Materiales ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 340, 22);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Material:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 47, 14);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Valor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 32, 14);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Cantidad:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 60, 14);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Descuento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 59, 14);

        txt_nombre.setBackground(new java.awt.Color(204, 255, 204));
        txt_nombre.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 102, 102));
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(80, 50, 46, 21);

        txt_valor.setBackground(new java.awt.Color(204, 255, 204));
        txt_valor.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        txt_valor.setForeground(new java.awt.Color(51, 0, 204));
        txt_valor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_valor);
        txt_valor.setBounds(80, 100, 46, 21);

        txt_cantidad.setBackground(new java.awt.Color(204, 255, 204));
        txt_cantidad.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        txt_cantidad.setForeground(new java.awt.Color(51, 0, 204));
        txt_cantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cantidad);
        txt_cantidad.setBounds(80, 140, 46, 21);

        txt_descuento.setBackground(new java.awt.Color(204, 255, 204));
        txt_descuento.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        txt_descuento.setForeground(new java.awt.Color(51, 0, 204));
        txt_descuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_descuento);
        txt_descuento.setBounds(80, 190, 46, 21);

        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Total");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 0)));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 240, 40, 17);

        C_subtotal.setBackground(new java.awt.Color(204, 204, 204));
        C_subtotal.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        C_subtotal.setForeground(new java.awt.Color(0, 102, 102));
        C_subtotal.setText("Subtotal");
        C_subtotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        C_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(C_subtotal);
        C_subtotal.setBounds(210, 50, 55, 21);

        T_Iva.setBackground(new java.awt.Color(204, 204, 204));
        T_Iva.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        T_Iva.setForeground(new java.awt.Color(0, 102, 102));
        T_Iva.setText("Total con Iva");
        T_Iva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        T_Iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_IvaActionPerformed(evt);
            }
        });
        getContentPane().add(T_Iva);
        T_Iva.setBounds(200, 110, 79, 21);

        T_Descuento.setBackground(new java.awt.Color(204, 204, 204));
        T_Descuento.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        T_Descuento.setForeground(new java.awt.Color(0, 102, 102));
        T_Descuento.setText("Total con Descuento");
        T_Descuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        T_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_DescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(T_Descuento);
        T_Descuento.setBounds(180, 160, 127, 21);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vector-fondo-ladrillo-blanco-rustico_1453-216.jpg"))); // NOI18N
        jLabel7.setText(".");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 340, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_valorActionPerformed

    private void C_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_subtotalActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText();
        double valor = Double.parseDouble(txt_valor.getText());
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        double descuento = Double.parseDouble(txt_descuento.getText());
        Factura fa = new Factura(nombre,cantidad,valor,descuento);
        fa.Subtotal_t();
        jLabel6.setText(String.valueOf(fa.getSubtotal()));
        
        
        
        
    }//GEN-LAST:event_C_subtotalActionPerformed

    private void T_IvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_IvaActionPerformed
        // TODO add your handling code here:
        String nombre = txt_nombre.getText();
        double valor = Double.parseDouble(txt_valor.getText());
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        double descuento = Double.parseDouble(txt_descuento.getText());
        Factura fa = new Factura(nombre,cantidad,valor,descuento);
        fa.Total_Iva();
        jLabel6.setText(String.valueOf(fa.getTo_Iva_12()));  
        
    }//GEN-LAST:event_T_IvaActionPerformed

    private void T_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_DescuentoActionPerformed
        // TODO add your handling code here:
          String nombre = txt_nombre.getText();
        double valor = Double.parseDouble(txt_valor.getText());
        int cantidad = Integer.parseInt(txt_cantidad.getText());
        double descuento = Double.parseDouble(txt_descuento.getText());
        Factura fa = new Factura(nombre,cantidad,valor,descuento);
        fa.Total_Descuento();
        jLabel6.setText(String.valueOf(fa.getT_Descuento()));
    }//GEN-LAST:event_T_DescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_subtotal;
    private javax.swing.JButton T_Descuento;
    private javax.swing.JButton T_Iva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}

